### ISSUE TITLE
Cannot test fastlin due to error "get_barcodes.rs:45:30"

### ISSUE THREAD

**Issue by carlosmag** [rderelle/fastlin#1]
Hi! I would love to test fastlin, but I am getting the following error with standard MTBC barcodes.

`fastlin` -d . -b barcodes-fastlin/MTBC_barcodes.tsv

 fastlin thread 'main' panicked at 'byte index 88 is out of bounds of `ATCGCCAGCAGTATCGAACGCAATATCCGTGAACTCGAGGGCGCGCTGAT`', src/get_barcodes.rs:45:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace . get barcodes and genome size`

Note: running conda version

**Comment by rderelle** [comment]
Hi,

my apologies, I modified the length of kmers in the MTBC barcode file but forgot to update fastlin's code accordingly. It will work fine with version 0.2.0. 

nb: not yet available in Conda as I'm trying to add fastlin to the Bioconda channel

best wishes,
Romain

**Comment by carlosmag** [comment]
It works now, thanks!!
